name: jekyll-reveal 
markdown: redcarpet
highlighter: pygments

baseurl: /rpip-cursus

collections:
  slides:
    output: true
  labs:
    output: true

defaults:
  - scope:
      path: ""
      type: labs
    values:
      layout: labs
  - scope:
      path: ""
      type: slides
    values:
      layout: slides
      reveal:
        controls: true
        progress: true
        slideNumber: true
        history: false
        keyboard: true
        overview: true
        center: true
        touch: true
        loop: false
        rtl: false
        fragments: true
        embedded: false
        autoSlide: 0
        autoSlideStoppable: true
        mouseWheel: false
        hideAddressBar: true
        previewLinks: false
        transition: default
        transitionSpeed: default
        backgroundTransition: default
        viewDistance: 3
        parallaxBackgroundImage:
        parallaxBackgroundSize:
        theme: moon
        width: 1920
        height: 1080
        margin: 0.1
